version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore:"
    labels:
      - "dependabot: ecosystem : github actions"
      - "dependabot: dependencies"
    assignees:
      - "TGWolf"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      day: "monday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore:"
    labels:
      - "dependabot: ecosystem : python"
      - "dependabot: dependencies"
    assignees:
      - "TGWolf"

